### ISSUE TITLE
Save order

### ISSUE THREAD

**Issue by mvchn** [trngl8/library-project#107]
Order must sent to processing after save.

1. Use .env, set URI_PROCESSING_ADDRESS (http://servername.com/api/order/create)
2. send a HTTP request to the remote server 
3. if status_code 200 and json is valid then Thanks to order, else Processing failed

sample response from the remote server:
```
{
  "status": "new"
}
```

A env and a requests dependencies may be installed.

**Comment by roman-duck** [comment]
there is working endpoint for testing on https://triangle.software/api/order/create
